### ISSUE TITLE
Add a 'dry-run' mode

### ISSUE THREAD

**Issue by drewblas** [ZZROTDesign/docker-clean#10]
It would be very helpful to see everything that WOULD be deleted first without actually deleting it all

**Comment by killianbrackey** [comment]
**Edit: This pre-release is now fully implemented in realease v1.4.0 and up**

Thanks for pointing this out! Definitely a useful feature.  Dry run is now up and running as a development release in our dry-run branch.  The release is a rough release right now (printing out some raw data) so I am going to keep this issue open until a full release.  We are currently working to re-vamp the command line options to better accommodate the needs of other users.  However, if you are interesting in seeing how this runs currently without consequence this release will do just that for you.  Details regarding the release and how to install are available on the pre-release page: 

https://github.com/ZZROTDesign/docker-clean/releases/tag/v1.3.2.R0

For a full walk through of `docker-clean --dry-run` check out the [USAGE.md](https://github.com/ZZROTDesign/docker-clean/blob/dry-run/USAGE.md)

**Comment by drewblas** [comment]
Fantastic!  Thanks!

**Comment by killianbrackey** [comment]
Absolutely! The dry run is now fully functional in the new realease: docker-clean v1.4.0.
