### ISSUE TITLE
Linux support please!

### ISSUE THREAD

**Issue by anaibol** [ZZROTDesign/docker-clean#14]
_If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template._
#### 5. What are your system specs?

Docker Version:
Docker-Machine Version:
OS/Version:

**Comment by killianbrackey** [comment]
What types of errors are you getting and which distro are you using?  It has been built with cross platform portability.  If you wouldn't mind filling out some of the questions in the template it would make it much easier to troubleshoot your issue.

**Comment by anaibol** [comment]
Hi, I am very sorry, it was an issue with Docker, the script is working correctly. Thanks for your support and sorry again!
