### ISSUE TITLE
[Question] Any chance to implement only remove images option?

### ISSUE THREAD

**Issue by d6u** [ZZROTDesign/docker-clean#15]
I have a use case where in development I want to keep running, exited and created containers, and only remove images that are not used by them.

Apologies for not knowing bash well enough to make a PR.

**Comment by killianbrackey** [comment]
We are currently in the process of overhauling our flags to allow for more flexible options so this should be an option in our new release!

**Comment by killianbrackey** [comment]
If you take a chance to look through some of the new options you will be able to make this work.  If you are simply looking to remove unused images running `docker-clean -i -t` (or --images --tagged) will remove all untagged and tagged images that aren't being used by any containers and will not remove anything else.  Trying with a `--dry-run` will demonstrate this for you as well, like this: `docker-clean -i -t -n`

Let us know if you have any questions or suggestions!

**Comment by d6u** [comment]
Awesome, thanks
