### ISSUE TITLE
docker-clean is not removing "Created" containers

### ISSUE THREAD

**Issue by jamshid** [ZZROTDesign/docker-clean#18]
_If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template._
#### 1. What version of Docker-Clean are you running (`docker-clean --version`)?

2.0.4
#### 2. What command are you trying to run?

docker-clean
#### 3. What did you expect to see?

Created containers like this get deleted:

```
c40b50fd725e        c0c490b65679                                                "/bin/sh -c '#(nop) V"   24 hours ago        Created                                                                    distracted_bell
```
#### 4. What did you see instead ( 'docker-clean -l or --verbose' for the entire log )?

$ docker-clean -l
Cleaning images...
DELETED: REPOSITORY/TAG: [] IMAGE ID: afa91711ce87
Images cleaned: 1
You've cleared approximately MB: 726 of space!
No dangling volumes!
Removing empty networks...
Error response from daemon: network 2a52733d35db 1099cf15fad1 d643b953957e 8e5cd7ac7807 eaeb7e2b7710 not found
Networks removed: 1
#### 5. What are your system specs?

Docker Version: 1.11.2 server (Ubuntu 14.04.4 LTS, 3.13.0-85-generic, aufs)
Docker client: 1.11.1
Docker-Machine Version: n/a
OS/Version: OSX

---

Using this as a workaround:

```
function dclean() { docker ps -q -a -f status=exited | xargs -n 100 docker rm -v ; docker ps -q -a -f status=created | xargs -n 100 docker rm -v ; docker images -q --filter "dangling=true" | xargs -n 100 docker rmi ; }
```

**Comment by kilpatty** [comment]
hey jamshid, I apologize for the delayed response, we've been quite busy these past few days! Later today I'm going to check your issue out, and hopefully get you an answer (and fix) by tonight!

**Comment by killianbrackey** [comment]
In order to remove containers, you will need to run docker clean with the -c --containers flag.  Here is an example with a 

<img width="1101" alt="screen shot 2016-06-12 at 9 00 38 pm" src="https://cloud.githubusercontent.com/assets/14007243/15997167/6ec3cbe8-30f6-11e6-8ff1-37abeec5f9c6.png">

I am going to go ahead and close this issue, but feel free to re-open if created containers still aren't being removed.

**Comment by killianbrackey** [comment]
Also, if you have any suggestions on how we could clarify this with our documentation let us know!
