### ISSUE TITLE
bad version number in latest release

### ISSUE THREAD

**Issue by guillaumevincent** [ZZROTDesign/docker-clean#21]
![screenshot from 2016-06-15 10-37-24](https://cloud.githubusercontent.com/assets/943762/16073294/8b9c1450-32e5-11e6-8fcd-da1fb1c0ea06.png)

is there an error in version number v1.4.0 for tag v2.0.4 ?

**Comment by killianbrackey** [comment]
Thanks for pointing this out -- has been fixed!
