### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by pascalandy** [ZZROTDesign/docker-clean#25]
Hey guys,

Really appreciated your work! I was curious to find that this image size is that big. Have your tried FROM alpine:3.4 ?

```
zzrot/docker-clean   latest              26c88e88101d        12 weeks ago        108.3 MB
```

--- 

#### 1. What version of Docker-Clean are you running (` docker-clean --version`)?
2.0.4

#### 5. What are your system specs?

OS/Version: 
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

**Comment by killianbrackey** [comment]
Hey @pascalandy thanks for pointing this out.  This addition was originally a PR to add this to an image but we can take a look at baking it into an alpine image instead of the base Docker image.  I will take a look and keep you in the loop!

**Comment by pascalandy** [comment]
Very cool! Many optimized image is see around between 8 to 19 MO :)

Cheers!

**Comment by killianbrackey** [comment]
Added a lite tag `zzrot/docker-clean:v2.0.4-lite`.  Some may be using more in the base alpine image that docker puts together but this image is down to 4MB 👍 

https://hub.docker.com/r/zzrot/docker-clean/tags/

**Comment by pascalandy** [comment]
Very good !!
