### ISSUE TITLE
Cannot run docker-clean using docker as per instructions

### ISSUE THREAD

**Issue by ferrarimarco** [ZZROTDesign/docker-clean#28]
#### 1. What version of Docker-Clean are you running (` docker-clean --version`)?
`latest` docker image tag (id: 91b2e956f1b4, created 3 weeks ago)

#### 2. What command are you trying to run?
From a newly installed docker instance on a "clean" VM: `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean`

#### 3. What did you expect to see?

> No Images to delete!
> No dangling volumes!
> No empty networks!

#### 4. What did you see instead ( 'docker-clean -l or --verbose' for the entire log )?
> docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/docker-clean/docker-clean\\\": stat /docker-clean/docker-clean: no such file or directory 

#### 5. What are your system specs?

Docker Version: 1.12.5
Docker-Machine Version: N/A
OS/Version: Ubuntu 16.04

**Comment by ferrarimarco** [comment]
@killianbrackey Hi. It seems that someone is having the same issue as reported on Gitter. If you share some details about the requirements of that Dockerfiles, I can provide a pull request to fix them

**Comment by killianbrackey** [comment]
Hey @ferrarimarco thanks for reporting the issue.  I am taking a look at this right now.  I was able to build and run the command locally so I am checking this against the context of the makefile

**Comment by ferrarimarco** [comment]
That's great :+1:

**Comment by killianbrackey** [comment]
Fix coming through the pipeline now, but the tag has been fixed.  A fresh pull of the image should work for you now @ferrarimarco 

```
$ docker pull zzrot/docker-clean:latest
$ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean
No images to delete!
No dangling volumes!
No empty networks!
```

**Comment by ferrarimarco** [comment]
Confirmed, it works!
