### ISSUE TITLE
Better Docker for Mac support

### ISSUE THREAD

**Issue by nikolay** [ZZROTDesign/docker-clean#35]
Docker for Mac is not necessarily working like Docker Machine. Currently, you get a sort of an error:

```
$ docker-clean -r
No active host found
Host does not exist: ""
Host does not exist: ""
Running docker-machine env ...
Error: No machine name(s) specified and no "default" machine exists
New IP Address for  :
```

**Comment by killianbrackey** [comment]
Thanks for pointing this out.  I just started noticing this on Docker for Mac on my machine as well.  I will take a look here

**Comment by josephpage** [comment]
For several weeks, I have no problem running docker-clean with Docker for Mac.

**Comment by nikolay** [comment]
@josephpage True, it's no longer an issue, so, I'm closing this.
