### ISSUE TITLE
'docker-clean stop' is clearing images

### ISSUE THREAD

**Issue by cowboygneox** [ZZROTDesign/docker-clean#36]
Perhaps this is just a documentation clarification, but with the "stop" command, I was not expecting images to be cleared.

Example output:
```
$ docker-clean stop
No running containers!
Cleaning containers...
Stopped containers cleaned: 2
Cleaning images...
Images cleaned: 1
You've cleared approximately MB: 1506 or GB: 1 of space!
Cleaning existing dangling volumes...
Volumes cleaned: 2
No empty networks!
```

*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template.*

#### 1. What version of Docker-Clean are you running (` docker-clean --version`)?
v2.0.4

#### 2. What command are you trying to run?
`stop`

#### 3. What did you expect to see?
Not images being cleared

#### 4. What did you see instead ( 'docker-clean -l or --verbose' for the entire log )?
Images being cleared

#### 5. What are your system specs?

Docker Version:
Docker-Machine Version:
OS/Version: Linux

**Comment by killianbrackey** [comment]
Thanks for pointing this out -- this looks like a documentation issue.  It is going to run the base commands which should only be clearing untagged images.  Did remove an image that was tagged by chance @cowboygneox ?

**Comment by cowboygneox** [comment]
@killianbrackey I don't believe so. What makes the default behavior different from adding `-i`?

**Comment by killianbrackey** [comment]
https://cl.ly/460m3b2b0M38

The default run and command runs (stop, all, etc) have some helpful/useful commands for local development.  The flags are around to allow for hand picked options that some users or we noticed might be nice to chain together for more specific purposes.  You can always run the dry run option to see what a run would be cleaning up if there is a gap or misunderstanding with the docs.

**Comment by cowboygneox** [comment]
So the answer to my question is that `stop` contains the functionality that `-i` provides?

**Comment by cowboygneox** [comment]
Don't you think that `images` should cover that and `stop` should not?

**Comment by killianbrackey** [comment]
Yeah I think that can make some sense.  The original top commands were designed around an older version of this script that people were expecting to run this way.  Best docker practices would say that all of your images should be tagged so for the most part the images cleaning is good one to run in local environments.  The command that you are looking for is `docker-clean -s -c`

**Comment by cowboygneox** [comment]
Good to know. Hopefully I provided some input for future versions.
